name: autofix.ci

on:
  pull_request:
    branches: [ master, main ]
    paths:
      - "frontend/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./frontend

jobs:
  autofix-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
          cache-dependency-path: "frontend"
      - run: |
          npm ci
          npx prettier --write .
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"

  lint:
    runs-on: ubuntu-latest
    needs: autofix-prettier
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "20"
          cache-dependency-path: "frontend"
      - run: |
          npm ci
          npx eslint . --max-warnings 0